easy_admin:
    design:
        # Changing the main backend color
#        brand_color: 'rgba(26, 188, 156, 0.85)'
        assets:
            # Changing the favicon (needs editing)
#            favicon: '/public/images/camera-lens.jpg'

        # Make the menu overview
#        menu:
#            - {label: "Albums"}
#            - label: "Albums"
#              children:
#                  - {entity: Album, label: "Album list", icon: "th-list"}
#                  - {entity: Album, label: "Add album", icon: "plus", params: {action: "new"}}
    site_name: "'t Klein Moment"
    user:
        display_name: true
        display_avatar: true
        # firstName resembles getFirstName() or 'firstName' in user
        # change to view anathor name when logged in
        name_property_path: 'firstName'
    list:
        title: '%%entity_label%% overview'
        collapse_actions: true
        actions:
            - { name: 'show', icon: 'info-circle', label: 'Show' }
            - { name: 'edit', icon: 'pencil', label: 'Edit' }
            - { name: 'delete', icon: 'trash-alt', label: 'Delete' }
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    entities:
        # List the entity class name you want to manage

        About:
            class: App\Entity\About
            label: 'About'
            list:
                help: 'Overview of the about page'
                fields:
                    - id
                    - header
                    - { property: 'image_path', label: 'Image path', type: 'image' }
                    - text
            form:
                fields:
                    - tableName
                    - header
                    - { property: 'image_path', label: 'Image path'}
                    - imageName
                    - { property: 'text', type: 'text_editor'}

        Album:
            class: App\Entity\Album
            label: 'Album'
            list:
                help: 'Overview of all the albums'
                fields:
                    - id
                    - name
                    - location
                    - event
                    - date
                    - description
                    - { property: 'createdAt', label: 'Created at', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Updated at', type: 'datetime' }
                    - tags
            form:
                fields:
                    - name
                    - location
                    - event
                    - date
                    - description
                    - user
                    - tags

        Contact:
            class: App\Entity\Contact
            label: 'Contact'
            list:
                help: 'Your contact information'
                fields:
                    - id
                    - name
                    - { property: 'email', type: 'email' }
                    - { property: 'phoneNumber', label: 'Phonenumber', type: 'tel' }
                    - { property: 'facebookLink', label: 'Facebook', type: 'url' }
                    - { property: 'instagramLink', label: 'Instagram', type: 'url' }

        DownloadLog:
            class: App\Entity\DownloadLog
            label: 'DownloadLog'
            disabled_actions: ['delete', 'new', 'edit']
            list:
                help: 'Overview of all the downloaded images. When and by who'
                fields:
                    - id
                    - user
                    - { property: 'user.name', label: 'User name' }
                    - image
                    - { property: 'downloadedAt', label: 'Downloaded at', type: 'datetime' }

        Image:
            class: App\Entity\Image
            label: 'Image'
            list:
                help: 'Overview of all the images'
                fields:
                    - id
                    - { property: 'path', type: 'image'}
                    - description
                    - alt
                    - size
                    - { property: 'uploadedAt', label: 'Uploaded at', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Updated at', type: 'datetime' }
            form:
                fields:
                    - { property: 'path'}
                    - description
                    - alt
                    - size

        Like:
            class: App\Entity\Like
            label: 'Like'
            disabled_actions: ['delete', 'new', 'edit']
            list:
                help: 'Overview of all the liked images'
                fields:
                    - id
                    - user
                    - { property: 'user.name', label: 'User name' }
                    - image
                    - { property: 'date', type: 'datetime' }

        Message:
            class: App\Entity\Message
            label: 'Message'
            disabled_actions: ['delete', 'new']
            list:
                help: 'Overview of all messages sent to you by members and non-members'
                fields:
                    - id
                    - sender
                    - { property: 'phoneNumber', label: 'Phone number', type: 'tel' }
                    - text
                    - { property: 'sentAt', label: 'Send date', type: 'datetime' }

        Tag:
            class: App\Entity\Tag
            label: 'Tag'
            list:
                help: 'Overview of all the tags that can be added to an album and/or image'
                fields:
                    - id
                    - description
            form:
                fields:
                    - description
                    - albums

        User:
            class: App\Entity\User
            label: 'User'
            disabled_actions: ['delete']
            list:
                help: 'Overview of all the users of your site'
                fields:
                    - id
                    - name
                    - { property: 'cosplayName', label: 'Cosplay name' }
                    - { property: 'email', type: 'email' }
                    - roles
                    - { property: 'createdAt', label: 'Created at', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Updated At', type: 'datetime' }

