easy_admin:
    design:
        assets:
            # Changing the favicon (needs editing)
            favicon: '/img/favicon-camera.jpg'

            # adding custom css to dashboard
            css: [ 'css/admin_backend.css']

        # Make the menu overview
        menu:
            - label: "Albums"
              icon: 'image'
              children: ['Album', 'Image', 'Tag']
            - label: 'About'
              icon: 'address-card'
              children: ['About', 'Contact']
            - label: 'Users'
              icon: 'user'
              children: ['User', 'Message']
            - label: 'Data'
              icon: 'chart-bar'
              children: ['Like', 'DownloadLog']
            - { label: 'API', url: 'https://wdev.be/wdev_roel/eindwerk/api', target: '_blank', icon: 'wrench'}
            - { label: 'Homepage', url: 'http://localhost:3000', target: '_blank', icon: 'desktop' }


    site_name: "'t Klein Moment"
    user:
        display_name: true
        display_avatar: true
        # firstName resembles getFirstName() or 'firstName' in user
        # change to view another name when logged in
        name_property_path: 'firstName'
    list:
        title: '%%entity_label%% overview'
        collapse_actions: true
        actions:
            - { name: 'show', icon: 'info-circle', label: 'Show' }
            - { name: 'edit', icon: 'pencil', label: 'Edit' }
            - { name: 'delete', icon: 'trash-alt', label: 'Delete' }
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    entities:
        # List the entity class name you want to manage

        Album:
            class: App\Entity\Album
            label: 'Album'
            list:
                help: 'Overview of all the albums'
                fields:
                    - id
                    - active
                    - name
                    - location
                    - event
                    - date
                    - description
                    - { property: 'createdAt', label: 'Created at', type: 'datetime' }
                    - tags
                    - images
            show:
                fields:
                    - id
                    - name
                    - location
                    - event
                    - date
                    - description
                    - tags
                    - images
                    - { property: 'createdAt', label: 'Created at', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Updated at', type: 'datetime' }
            form:
                fields:
                    - name
                    - location
                    - event
                    - { property: 'date', type_options: { widget: single_text }}
                    - description
                    - user
                    - tags
                    - {property: 'images', type: 'collection', type_options: {entry_type: 'App\Form\AlbumType' , 'by_reference': false}}

        About:
            class: App\Entity\About
            label: 'About'
            list:
                help: 'Overview of the about page'
                fields:
                    - id
                    - header
                    - { property: 'image', type: 'image', base_path: '%app.path.about_images%'}
                    - text
            form:
                fields:
                    - tableName
                    - header
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'text', type: 'text_editor'}

        Contact:
            class: App\Entity\Contact
            label: 'Contact'
            list:
                help: 'Your contact information'
                fields:
                    - id
                    - name
                    - { property: 'email', type: 'email' }
                    - { property: 'phoneNumber', label: 'Phonenumber', type: 'tel' }
                    - { property: 'facebookLink', label: 'Facebook', type: 'url' }
                    - { property: 'instagramLink', label: 'Instagram', type: 'url' }

        DownloadLog:
            class: App\Entity\DownloadLog
            label: 'DownloadLog'
            disabled_actions: ['delete', 'new', 'edit']
            list:
                help: 'Overview of all the downloaded images. When and by who'
                fields:
                    - id
                    - user
                    - { property: 'user.name', label: 'User name' }
                    - image
                    - { property: 'downloadedAt', label: 'Downloaded at', type: 'datetime' }

        Image:
            class: App\Entity\Image
            label: 'Image'
            list:
                help: 'Overview of all the images'
                fields:
                    - id
                    - active
                    - { property: 'image', type: 'image', base_path: '%app.path.album_images%'}
                    - description
                    - alt
                    - albums
                    - { property: 'uploadedAt', label: 'Uploaded at', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Updated at', type: 'datetime' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.album_images%'}
                    - id
                    - description
                    - albums
                    - alt
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - description
                    - { property: 'albums', type_options: { by_reference: false } }
                    - alt

        Like:
            class: App\Entity\Like
            label: 'Like'
            disabled_actions: ['delete', 'new', 'edit']
            list:
                help: 'Overview of all the liked images'
                fields:
                    - id
                    - user
                    - { property: 'user.name', label: 'User name' }
                    - image
                    - { property: 'date', type: 'datetime' }

        Message:
            class: App\Entity\Message
            label: 'Message'
            disabled_actions: ['delete', 'new']
            list:
                help: 'Overview of all messages sent to you by members and non-members'
                fields:
                    - id
                    - {property: 'answered', type: 'toggle'}
                    - sender
                    - { property: 'phoneNumber', label: 'Phone number', type: 'tel' }
                    - text
                    - { property: 'sentAt', label: 'Send date', type: 'datetime' }
            edit:
                fields:
                    - answered

        Tag:
            class: App\Entity\Tag
            label: 'Tag'
            list:
                help: 'Overview of all the tags that can be added to an album and/or image'
                fields:
                    - id
                    - description
                    - albums
            form:
                fields:
                    - description
                    - { property: 'albums', type_options: { by_reference: false } }

        User:
            class: App\Entity\User
            label: 'User'
            disabled_actions: ['delete']
            list:
                help: 'Overview of all the users of your site'
                fields:
                    - id
                    - name
                    - { property: 'cosplayName', label: 'Cosplay name' }
                    - { property: 'email', type: 'email' }
                    - roles
                    - { property: 'createdAt', label: 'Created at', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Updated At', type: 'datetime' }
            show:
                fields:
                    - id
                    - firstName
                    - lastName
                    - cosplayName
                    - email
                    - roles
                    - createdAt
                    - updatedAt
                    - downloadLogs
                    - likes
            form:
                fields:
                    - email
                    - firstName
                    - lastName
                    - cosplayName
                    - password
                    - { property: 'plainPassword', label: 'Password' }
                    - regkey

