security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        # Frontend login & security
        login:
            pattern:   ^/api/login_check
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
#                username_path: email
#                password_path: password
                success_handler:    lexik_jwt_authentication.handler.authentication_success
                failure_handler:    lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

#   only accessable when send with JWT token
#        api:
#            pattern: ^/api
#            stateless: true
#            guard:
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Admin dashboard login & security
        admin:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator
                entry_point: App\Security\AdminAuthenticator
            logout:
                path: app_logout
                target: app_login       # on logout you are redirected tot the loginpage

        main:
            anonymous: lazy
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:

        # access restriction for api endpoints
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # access restriction for admin dashboard
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }

#       when firewall api is active
#        - { path: ^/api/download_logs, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/likes, roles: IS_AUTHENTICATED_FULLY }


