vich_uploader:
    db_driver: orm

    mappings:
        album_images:
#            uri_prefix: 'https://wdev.be/wdev_roel/eindwerk/img/albums'
            uri_prefix: '%app.path.album_images%'                           # base_path that is defined in services.yaml
            upload_destination: '%kernel.project_dir%/public/img/albums'    # location where the image will be uploaded to
            namer: Vich\UploaderBundle\Naming\OrignameNamer                 # Gives every image an unique prefix
        about:
#            uri_prefix: 'https://wdev.be/wdev_roel/eindwerk/img/about'
            uri_prefix: '%app.path.about_images%'
            upload_destination: '%kernel.project_dir%/public/img/about'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

