vich_uploader:
    db_driver: orm

    # mapping where all images can be found and saved to
    mappings:
        album_images:
            uri_prefix: '%app.path.album_images%'                           # base_path that is defined in services.yaml
            upload_destination: '%kernel.project_dir%/img/albums'           # location where the image will be uploaded to
            namer: Vich\UploaderBundle\Naming\OrignameNamer                 # Gives every image an unique prefix
        about_images:
            uri_prefix: '%app.path.about_images%'
            upload_destination: '%kernel.project_dir%/img/about'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        album_covers:
            uri_prefix: '%app.path.album_covers%'
            upload_destination: '%kernel.project_dir%/img/covers'
            namer: Vich\UploaderBundle\Naming\OrignameNamer


