#register:
#  path: /api/register
#  controller: App\Controller\AuthController::register
#  methods: [POST]

user_login:
  path:     /api/login_check
  methods:  [POST]

#app_login:
#  path: /admin/login
#  controller: App\Controller\SecurityController::login
#
#app_logout:
#  path: /admin/logout
#  methods: GET
